### ISSUE TITLE
Would be nice to have a UUID resolver endpoint

### ISSUE THREAD

**Issue by gete76** [iDigBio/idigbio-search-api#10]
Would like to see an endpoint that resolves a UUID to a record without knowing the type. This would require adding a type key to the record for discovery info.

**Comment by godfoder** [comment]
Should be working now:

http://beta-search.idigbio.org/v2/view/5766da97-14a3-48b0-aa54-1daa71bb66bc

I also added a "type" parameter to most/all of the record returns.
