### ISSUE TITLE
Using both fields and fields_exclude in searchs for media gives unexpected results

### ISSUE THREAD

**Issue by mjcollin** [iDigBio/idigbio-search-api#11]
When running a media search, specifying a fields_exclude parameter turns fields into a list of excluded fields. Specifying only fields or fields_exclude works correctly:

Good:

http://beta-search.idigbio.org/v2/search/media/?rq={%22genus%22:%22cortinarius%22}&fields=[%22datemodified%22]&sort=%22uuid%22&limit=1

http://beta-search.idigbio.org/v2/search/media/?rq={%22genus%22:%22cortinarius%22}&fields_exclude=[%22data%22]&sort=%22uuid%22&limit=1

Bad:

http://beta-search.idigbio.org/v2/search/media/?rq={%22genus%22:%22cortinarius%22}&fields=[%22datemodified%22]&fields_exclude=[%22data%22]&sort=%22uuid%22&limit=1

**Comment by godfoder** [comment]
fixed in latest commit.
