### ISSUE TITLE
Lat & long flipped for some records without the rev_geocode_flip DQS flag

### ISSUE THREAD

**Issue by mjcollin** [iDigBio/idigbio-search-api#13]
See for instance uuid 0e6cdbf0-ada5-4435-bc9a-b1db99db6142.

A R client search that shows some examples of flipped and unflipped lat & lon:

df <- idig_search_records(rq=list("genus"="acer", "flags"="rev_geocode_mismatch"), fields=c("uuid", "flags", "geopoint", "data.dwc:decimalLongitude", "data.dwc:decimalLatitude"), limit=10)

**Comment by godfoder** [comment]
This should be fixed in the latest commit (1f47398), testing to make sure.

**Comment by godfoder** [comment]
Fixed now.
