### ISSUE TITLE
Portal query not returning indexed fields for some records

### ISSUE THREAD

**Issue by melanostomias** [iDigBio/idigbio-search-api#15]
When doing a search for some records from Laos collected by UF Fish Collection I found a set of records that had not been fully indexed (specifically with iso countrycode). This brings to question which other records have not been indexed with this field or a similar field. This particular recordset: UF FLMNH Ichthyology (https://www.idigbio.org/portal/recordsets/c38b867b-05f3-4733-802e-d8d2d3324f84) has most of it's records indexed, but not the ones from Laos (and possibly others). 

To reproduce the records in question I put "UF" in Institution Code and "Laos" in Country. All 29 records are missing iso countrycode. Doing another country like "Mexico" gives back records with an iso countrycode "mex".

**Comment by kevinlove** [comment]
To further this example, LAO is not in the summary:

http://search.idigbio.org/v2/summary/top/records/?rq={%22recordset%22:%22c38b867b-05f3-4733-802e-d8d2d3324f84%22,%22collectioncode%22:%22fish%22,%22institutioncode%22:%22uf%22}&top_fields=[%22countrycode%22]&count=300

**Comment by godfoder** [comment]
Some more background, the official name of Laos is "Lao People's Democratic Republic". I have added a correction for the more common name in the US to the proper name. This will eventually show up, although I will need to refresh the correction tables then run a full re-index, so it probably won't be for a couple of weeks.
