### ISSUE TITLE
Elasticsearch error when trying to pull windows larger than 10k records.

### ISSUE THREAD

**Issue by godfoder** [iDigBio/idigbio-search-api#18]
See: http://search.idigbio.org/v2/search/records?offset=10000&limit=7

[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [10007]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter. :: {"path":"/idigbio-2.9.3/records/_search","query":{"sort":"dqs:desc","size":7,"from":10000},"body":"{\"query\":{\"filtered\":{\"filter\":{}}},\"aggs\":{\"rs\":{\"terms\":{\"field\":\"recordset\",\"size\":1000}},\"max_dm\":{\"max\":{\"field\":\"datemodified\"}}}}","statusCode":500,"response":"{\"error\":{\"root_cause\":[{\"type\":\"query_phase_execution_exception\",\"reason\":\"Result window is too large, from + size must be less than or equal to: [10000] but was [10007]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"idigbio-2.9.3\",\"node\":\"nEKfKozIR56qIIGcR-R6UA\",\"reason\":{\"type\":\"query_phase_execution_exception\",\"reason\":\"Result window is too large, from + size must be less than or equal to: [10000] but was [10007]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.\"}}]},\"status\":500}"}
   at respond (/var/www/node/idigbio-search-api/node_modules/elasticsearch/src/lib/transport.js:289:15)
   at checkRespForFailure (/var/www/node/idigbio-search-api/node_modules/elasticsearch/src/lib/transport.js:248:7)
   at HttpConnector.<anonymous> (/var/www/node/idigbio-search-api/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
   at IncomingMessage.wrapper (/var/www/node/idigbio-search-api/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)

**Comment by godfoder** [comment]
It looks like this changed to push users towards the scroll API in elasticsearch 2.x . May require substantial re-engineering to accomplish large paging. Tweaking the max_result_window parameter will just mask the issue for small result sizes, but we'd still need a cap somewhere to prevent the error in all cases.

**Comment by mjcollin** [comment]
Results window upped to 50k yesterday to defer the consequences of this but it still needs a reworking on the API's backend code to make windowing the dataset possible.

**Comment by mjcollin** [comment]
Can we bump the window to 100k? Then at least we're consistent with Gbif and the R client.

Perhaps we can revisit this in combination with the download API. I was never fully happy with paging due to the need to default sort on uuid.

Matthew Collins
________________________________

**Comment by godfoder** [comment]
Set to 100k now, and hopefully persistent across index rebuilds.
