### ISSUE TITLE
too much data quality control?

### ISSUE THREAD

**Issue by fmichonneau** [iDigBio/idigbio-search-api#19]
I'm trying to do a general query on US echinoderms, but I was getting a bunch records inland. Looking closer, I see a lot of fungi and plants even when asking specifically for kingdom="Animalia". For instance this zoomed-in query on Gainesville brings some fungi:

```
http://search.idigbio.org/v2/search/records?rq={%22kingdom%22:%20%22animalia%22,%20%22phylum%22:%20%22echinodermata%22,%20%22basisofrecord%22:%20%22preservedspecimen%22,%20%22geopoint%22:%20{%22type%22:%20%22geo_bounding_box%22,%20%22top_left%22:%20{%20%22lat%22:%20%2229.788%22,%20%22lon%22:%20%22-82.5183%22},%20%22bottom_right%22:%20{%22lat%22:%20%2229.592%22,%20%22lon%22:%20%22-82.2875%22}}}
```

Looking at it in more detail, for instance this record: https://www.idigbio.org/portal/records/3ca32a40-ab44-4812-9a7f-ca20a3cf30b9

it seems that the raw record indicates that it's a fungus, but during the data quality control, it gets re-assigned to the phylum "echinodermata".
1. is it possible to ask the API to do the query on the raw data to avoid these records?
2. it might be worth being extra careful when re-assigning taxonomic group to a different kingdom to be sure that it's going to improve the data.

**Comment by danstoner** [comment]
A lot of work has been completed since this issue was opened, records are much less likely to "jump" between taxonomic groups.

The example record now correctly appears as "fungi" in iDigBio.
