### ISSUE TITLE
Beta-search requires Content-Type header to be set for posting JSON searches

### ISSUE THREAD

**Issue by mjcollin** [iDigBio/idigbio-search-api#23]
When posting a JSON object containing parameters for a search eg:

`{rq:{"genus":"acer"},limit:10}`

the parameters will be ignored unless the Content-Type header is set to application/json in the current beta-search version of the API code. This used to work.

**Comment by mjcollin** [comment]
Content-Type was always supposed to be set, this must have been a bug in the implementation that allowed it to work previously. This effected the ridigbio package which will be updated shortly before beta is moved in to production.

**Comment by UnwashedMeme** [comment]
Yes; you need to express the correct content-type on post requests; accepted types are:
* `application/x-www-form-urlencoded`
* `application/json`
