### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by kevinlove** [iDigBio/idigbio-search-api#26]
Getting an error I have not seen before on the download system:

https://api.idigbio.org/v2/download/42055c3e-3c16-4cd4-8a3b-163b38709b8c

**Comment by danstoner** [comment]
The error:

`error: "[Errno 28] No space left on device: '/tmp/tmp8cLXqv'",`

**Comment by danstoner** [comment]
Disk space issue resolved.

@kevinlove that job looks to be "complete" with "FAILURE" status. I believe you will need to try the download again.

**Comment by godfoder** [comment]
You might have to wait 24 hours, I'm not sure the system is smart enough to clear the failed status.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by UnwashedMeme** [comment]
Give it a try, dealing with job requests on previously failed jobs was one
of the things that tried to fix in my last pass through there

**Comment by kevinlove** [comment]
Forgot to comment, but was able to create a new download without any issues. Thanks.
