### ISSUE TITLE
Summary API seems to be fixed to scientific name

### ISSUE THREAD

**Issue by ammatsun** [iDigBio/idigbio-search-api#5]
The example:
http://beta-search.idigbio.org/v2/summary/top/records/?fields=%5B%22kingdom%22%2C+%22phylum%22%5D 

is currently returning top scientificname.

Tried to change fields to other values and response seems to be always the same, based on scientificname.

{
scientificname: {
aleocharinae: {
itemCount: 52369
},
peromyscus maniculatus: {
itemCount: 48786
},
hymenoptera: {
itemCount: 46545
},
unidentified: {
itemCount: 45565
},
curculionidae: {
itemCount: 35838
},
plethodon cinereus: {
itemCount: 35289
},
undetermined: {
itemCount: 34865
},
aphodius: {
itemCount: 34697
},
diptera: {
itemCount: 34667
},
uta stansburiana: {
itemCount: 31430
}
},
itemCount: 27652650
}

**Comment by mjcollin** [comment]
The correct parameter is "top_fields". We changed this parameter name a couple months ago and I thought I updated all the examples. Where did you find one with "fields"?

Also, see the other open ticket #4 . We're working on that one.

**Comment by ammatsun** [comment]
It is in:
https://github.com/iDigBio/idigbio-search-api/wiki/Examples

**Comment by mjcollin** [comment]
Fixed. I blame Dan.

**Comment by danstoner** [comment]
The Examples page is generated.

[//]: # (THIS CONTENT IS GENERATED BY CODE. DO NOT EDIT VIA GITHUB "EDIT" IN BROWSER.)
